[project]
name = "plangs"
version = "0.1.0"
description = "A search engine for programming languages"
authors = ["Emmanuel Oga <contact@emmanueloga.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
sqlint = { cmd = "sqlfluff lint --dialect duckdb db/sql" }

[dependencies]
python = ">=3.12.2,<3.13"
ipython = ">=8.22.2,<8.23"
go = ">=1.22.2,<1.23"
sqlfluff = ">=3.0.5,<3.1"
python-duckdb = ">=0.10.2,<0.11"
rich = ">=13.7.1,<13.8"
sourcetypes = ">=0.0.4,<0.1"

[pypi-dependencies]
kuzu = "*"
msgspec = "*"
