[project]
name = "plangs"
version = "0.1.0"
description = "Add a short description here"
authors = ["Emmanuel Oga <contact@emmanueloga.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
ipython = ">=8.22.2,<8.23"
go = ">=1.22.2,<1.23"

[pypi-dependencies]
kuzu = "*"
msgspec = "*"
