. "/Users/emmanueloga/dev/plangs/.pixi/envs/default/etc/conda/deactivate.d/deactivate_z60-go.sh"
export PATH="/Users/emmanueloga/dev/plangs/.pixi/envs/default/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/emmanueloga/go/bin:/Users/emmanueloga/.pixi/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/Users/emmanueloga/.orbstack/bin"
export CONDA_PREFIX="/Users/emmanueloga/dev/plangs/.pixi/envs/default"
export PIXI_PROJECT_ROOT="/Users/emmanueloga/dev/plangs"
export PIXI_ENVIRONMENT_PLATFORMS="osx-arm64"
export PIXI_PROJECT_VERSION="0.1.0"
export PIXI_PROMPT="(plangs) "
export PIXI_PROJECT_NAME="plangs"
export PIXI_PROJECT_MANIFEST="/Users/emmanueloga/dev/plangs/pixi.toml"
export PIXI_IN_SHELL="1"
export CONDA_DEFAULT_ENV="plangs"
export PIXI_ENVIRONMENT_NAME="default"
export PIXI_EXE="/Users/emmanueloga/.pixi/bin/pixi"
. "/Users/emmanueloga/dev/plangs/.pixi/envs/default/etc/conda/activate.d/activate_z60-go.sh"

